### PR TITLE
Nfultz/queue update

### PR DESCRIPTION
**Pull request by nfultz**
This PR contains the resolutions for R CMD check:
* Added basic examples
* Addressed all notes around ggplot aes() calls
* Added S3 methods to NAMESPACE and documentation pages.
* Fixed S3 methods to match generic (OBJECT -> x)
* Reverted old ggdag workaround and increased suggested version to 0.2.4

### CODE REVIEW

**Comment by nfultz** [comment]
Is `convert.wait.max(wait.max, K)` intended to be user facing, or is it just an internal helper method?

**Comment by ben-oneill** [comment]
This is just an internal helper method.  (I initially thought about copying its code directly into queue, but figured it would be easier to interpret by setting it as a separate function.

Basically, the goal of this helper function is to convert the input for wait.max into a matrix input of the correct size.  The queue function allows three types of inputs for wait.max:

 * A vector giving values that will apply identically to all of the users;
 * A function that will be used to compute a vector of values that will apply identically to all of the users; or
 * A matrix giving values for each of the users (allowing different maximum waiting time for different users).

The helper function converts each of these inputs into the third type (matrix) and then queue operates off this latter type.

Cheers,
Ben.

________________________________

**Comment by nfultz** [comment]
OK good, that's what I thought - to keep the NAMESPACE exports simple, we can just prefix internal methods with a dot "." and they won't be exported, and won't generate warnings about missing documentation.

**Comment by nfultz** [comment]
This is on CRAN so merging now

**Pull request merged**
