### PR TITLE
Call libraries in plot.data.mappings

### PR DESCRIPTION
**Pull request by ben-oneill**
Call library(ggdag) and library(ggplot2) in plot.data.mappings

### CODE REVIEW

**Review by nfultz — CHANGES_REQUESTED** [review]
This will be rejected by cran - you already use the `::` syntax below, so it should work ok.

**Comment by ben-oneill** [comment]
Can you try running the mapping plot on your machine and see if it works (without loading ggdag and ggplot2 first).  When I try running it on a blank R session, when I try to print the mapping I get the following error:

   Error in ggproto(NULL, self, scales = lapply(self$scales, function(s) s$clone())) :   could not find function "ggproto"

I think what is happening here is that there is something inside ggdag that is internally calling ggplot2 functions without using :: (i.e., assuming that the package is loaded).

Does it work for you?


________________________________

**Comment by nfultz** [comment]
I believe the issue is seeing is being caused by some helper methods in `ggdag:::ggplot.tidy_dagitty` not dispatching correctly - I've worked around this in #4 by calling fortify manually, but it brings me no joy.

@malcolmbarrett - is there a better / more correct way to use ggdag from a package?

**Comment by malcolmbarrett** [comment]
Likely a bug. Will you please file an issue in ggdag?

**Pull request closed without merging**
